server:
    port: 8763

eureka:
    instance:
        hostname: 111.230.196.33
        prefer-ip-address: true

    client:
        service-url:
            defaultZone: http://111.230.196.33:8761/eureka/,http://111.230.196.33:8762/eureka/

Spring:
    application:
        name: SpringCloudTest_EurekaServerTest_authenticating

security:
    basic:
        enabled: true
    user:
        name: cairuojin
        password: 123456
