server:
    port: 80

    servlet:
      jsp:
        init-parameters:
          development: true

logging:
    com.gjsyoung.SpringCloudTest: INFO


spring:
#    profiles:
#       active: dev

    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none

    datasource:     # 数据库地址
        url: jdbc:mysql://111.230.196.33:3306/SpringInAction?useSSL=false
        username: cairuojin
        password: 44052100
        driver-class-name: com.mysql.jdbc.Driver

    mvc:
        static:
            static-path-pattern: /**
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp