server:
    port: 8091

logging:
    com.gjsyoung.SpringCloudTest: DEBUG


spring:
#    profiles:
#       active: dev

    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none

    datasource:     # 数据库地址
        url: jdbc:mysql://111.230.196.33:3306/SpringInAction?useSSL=false
        username: cairuojin
        password: 44052100
        driver-class-name: com.mysql.jdbc.Driver

    mvc:
        static:
            static-path-pattern: /**
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

    application:
        name: SpringCloudTest-UserProvider

eureka:
    client:
        service-url:
            defaultZone: http://111.230.196.33:8761/eureka/,http://111.230.196.33:8762/eureka/,http://cairuojin:123456@111.230.196.33:8763/eureka/
    instance:
        prefer-ip-address: true
        hostname: user
        metadata-map:
            myname: cairuojin
            myage: 22