server:
    port: 8040

logging:
    com.gjsyoung.SpringCloudTest: DEBUG


spring:
    application:
        name: SpringCloudTest-gateway-zuul

eureka:
    client:
        service-url:
            defaultZone: http://111.230.196.33:8761/eureka/,http://111.230.196.33:8762/eureka/,http://cairuojin:123456@111.230.196.33:8763/eureka/
    instance:
        prefer-ip-address: true

zuul:
    routes:                                         #路由配置表示
        userroutes:                                  #路由名一
            path: /user/**                          #(针对微服务名称的)访问路径
            serviceId: SpringCloudTest-UserProvider        #微服务名称

        movieroutes:
            path: /movie/**
            serviceId: SpringCloudTest_MovieProvider_feign
    ignored-services:  '*'
