server:
    port: 8761

eureka:
    instance:
        hostname: 111.230.196.33
        prefer-ip-address: true

    client:
        service-url:
            defaultZone: http://111.230.196.33:8762/eureka/,http://cairuojin:123456@111.230.196.33:8763/eureka/

Spring:
    application:
        name: SpringCloudTest_EurekaServerTest_ha