server:
    port: 8762

eureka:
    instance:
        hostname: peer2
        prefer-ip-address: false

    client:
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka/,http://cairuojin:123456@localhost:8763/eureka/

Spring:
    application:
        name: SpringCloudTest_EurekaServerTest