server:
    port: 8762

eureka:
    instance:
        hostname: peer2
        prefer-ip-address: false

    client:
        service-url:
            defaultZone: http://111.230.196.33:8761/eureka/,http://cairuojin:123456@111.230.196.33:8763/eureka/

Spring:
    application:
        name: SpringCloudTest_EurekaServerTest